# pull official base image
FROM node:16.3.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json /app
COPY package-lock.json /app
RUN npm install 

# add app
COPY . /app

# transpile
RUN npx tsc

# start app
CMD ["npm", "run", "startApi"]